name: Deploy

# About this workflow:
# It is triggered on push events to branches production and testing. Then it performs a checkout of the current repo
# and sets up a node environment (v12). Following, it will run `npm ci` to build the package. Next, it will look at your
# commit message, if it includes '#patch', '#minor', or '#major' it will bump the package version accordingly.
# Finally, the `npm publish` command will be run, when on branch testing it will run `npm publish --tag beta` to publish
# it under the beta flag on npm. Note: if no '#patch', '#minor', or '#major' flag is present in the latest commit
# AND the package version is not bumped manually the publish step will fail because we can not publish to an existing
# version.

# GitHub repo configuration:
# 1. Go to Manage access and add 'Github Actions' team with role: admin.
# 2. If you have protected branches, go to Branches > edit protected branch > enable 'Restrict who can push to
#    matching branches' and add the 'athombv/github-actions' team.

# Note: make sure to commit package-lock.json, this is needed for `npm ci`.

# Defines the trigger for this action, in general you want it to run when pushing to production | testing. For more
# information see: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#about-workflow-events)
on:
  push:
    branches:
      - production
      - testing

jobs:
  deploy_to_npm:
    name: Deploy to NPM

    # Only run this job if initiator is not the Homey Github Actions Bot to prevent loops
    if: github.actor != 'HomeyGithubActionsBot'

    runs-on: ubuntu-latest
    steps:

      # Checks out the current repository.
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          #           ssh-key: ${{ secrets.SSH_KEY }}
          # The token below is only necessary if you want to push the version bump to a protected branch
          token: ${{ secrets.HOMEY_GITHUB_ACTIONS_BOT_PERSONAL_ACCESS_TOKEN }}

      # Set git config to reflect Homey Github Actions Bot user
      - name: Set up HomeyGithubActionsBot git user
        run: |
          git config --local user.email "sysadmin+githubactions@athom.com"
          git config --local user.name "Homey Github Actions Bot"

      # Configures a Node.js environment.
      - name: Set up node 12 environment
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          # Needed for publishing to npm
          registry-url: 'https://registry.npmjs.org'

      # Only use the ssh-agent action below if your repository has private git dependencies (see README.md for instructions on how to configure an ssh key).
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # Run `npm ci && npm run build` to re-create your local environment (make sure to commit your - package-lock.json!).
      - name: Build
        run: |
          npm ci
          npm run build

#      - name: Version bump patch
#        if: "contains(github.event.head_commit.message, '#patch') && !contains(github.event.head_commit.message, '#minor') && !contains(github.event.head_commit.message, '#major')"
#        run: |
#          npm version patch
#          git pull
#          git push --follow-tags

#      - name: Version bump minor
#        if: "contains(github.event.head_commit.message, '#minor') && !contains(github.event.head_commit.message, '#major')"
#        run: |
#          npm version minor
#          git pull
#          git push --follow-tags

#      - name: Version bump major
#        if: "contains(github.event.head_commit.message, '#major')"
#        run: |
#          npm version major
#          git pull
#          git push --follow-tags

#      # Publish when this action is running on branch production
#      - name: Publish
#        if: github.ref == 'refs/heads/production'
#        run: |
#          npm publish
#          VERSION="$(node -p "require('./package.json').version")"
#          echo "::set-env name=package_version::${VERSION}"
#          echo $package_version
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

#      # Publish to beta when this action is running on branch testing
#      - name: Publish to beta
#        if: github.ref == 'refs/heads/testing'
#        run: |
#          npm publish --tag beta
#          VERSION="$(node -p "require('./package.json').version")@beta"
#          echo "::set-env name=package_version::${VERSION}"
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

#      # Post a Slack notification in #software on success/failure
#      - name: Slack notify
#        if: always()
#        uses: innocarpe/actions-slack@v1
#        with:
#          status: ${{ job.status }}
#          success_text: '${{github.repository}} - published v${{env.package_version}} to npm ðŸš€'
#          failure_text: '${{github.repository}} - failed to publish to npm'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Required

  deploy_to_github_pages:
    needs: deploy_to_npm

    if: github.ref == 'refs/heads/production'

    runs-on: ubuntu-latest

    name: Deploy Docs To GitHub Pages

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - run: npm install
      - run: npm run build

      - name: Deploy To GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          personal_token: ${{ secrets.HOMEY_GITHUB_ACTIONS_BOT_PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./build/docs
