name: ESLint

# GitHub repo configuration:
# 1. If you have protected branches, go to Branches > edit protected branch > enable 'Require status checks to pass before
#    merging' and select the 'ESLint' status check.

# Note: make sure to commit package-lock.json, this is needed for `npm ci`.

# Defines the trigger for this action (e.g. [pull_request, push])
# For more information see: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#about-workflow-events)
on:
  push:
    branches:
      - master
      - production
  pull_request:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      # Checks out the current repository.
      - uses: actions/checkout@v2
        with:
          # The token below is only necessary if you want to push the version bump to a protected branch
          token: ${{ secrets.HOMEY_GITHUB_ACTIONS_BOT_PERSONAL_ACCESS_TOKEN }}

      # Configures a Node.js environment.
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      # Only use the ssh-agent action below if your repository has private git dependencies (see README.md for instructions on how to configure an ssh key).
      # TODO: remove this step when possible
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # Run `npm ci` to re-create your local environment (make sure to commit your package-lock.json!).
      # Finally run `npm run lint` (make sure you have defined a lint command in package.json e.g. "lint": "eslint .").
      - run: npm ci
      - run: npm run lint